#!/usr/bin/env php

<?php
    require __DIR__.'/vendor/autoload.php';
    use Symfony\Component\Console\Application;
    use Tajawal\Commands\HotelsFinderCommand;

    $app = new Application('Tajawal Interview Task', 0.1);
    $app->add(new HotelsFinderCommand);

    $app->run();
    